### ISSUE TITLE
HTTPS/SSL issues

### ISSUE THREAD

**Issue by intelligentgoldfish-com** [FrozenStormInteractive/Unreal-SignalR#10]
Hi! I've been pulling my hair over this for a while and thought I'd ask here. Cloned this repository into my project Plugins folder. Everything seems to work OK, but there's an error when negotiating with the signalr hub. 

The hub is locally hosted (VS2022 Core WebApp), and works when using a browser with the same url. Both http and https. UE log gives me this error about SSL certificate:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/63851214/157262255-a3b36f09-118d-4695-9400-80025f098200.png">

Any ideas on how to solve this?

**Comment by intelligide** [comment]
I don't think libcurl uses the Windows certificate store. Try disabling ASP.NET Core HTTPS redirection in your development environment.

**Comment by intelligentgoldfish-com** [comment]
Yeah, I already tried that...without success!

**Comment by intelligentgoldfish-com** [comment]
Unchecking this checkbox makes the error disappear, but there's still no connection established. OnNegotiateResponse() is never executed...

<img width="510" alt="image" src="https://user-images.githubusercontent.com/63851214/157268950-5c731006-5115-4e5a-9f71-68b1e847fb6c.png">

**Comment by julegault** [comment]
i'm using the default chat hub example from microsoft, and the examples from this repo, and i'm getting the exact same error. Was the solution found ? 

I can also confirm the delegate is never called.

**Comment by intelligide** [comment]
I added a new [troubleshoot section](https://github.com/FrozenStormInteractive/Unreal-SignalR#troubleshooting) in the readme. Concretely, the problem comes from the fact that the functions are asynchronous and that the shared pointer removes the connection object and thus the connection with the server before the negotiation ended.
You just need to persist a reference to the connection object somewhere in your code to ensure that the object is not destroyed when the pointer is destroyed.
