### ISSUE TITLE
OnNegociateResponse never called

### ISSUE THREAD

**Issue by julegault** [FrozenStormInteractive/Unreal-SignalR#11]
Unreal 4.27.2

This is related to issue #10 and issue #6 because they both mention the same problem : OnNegociateResponse is never called in the provided code. refer to issue #6 for screenshots. I've been able to reproduce both issues. #10 happens with https connexion while #6 is easier to reproduce with http connexions

using a shared pointer with bindSP in connexion.cpp doesn't work, as the delegate is apparently never called. I tried changing it to bindRaw and it works, but the object the delegate is called on is a different one that has no populated attributes, so it ends up crashing too.

I don't know how to proceed to fix this, other than maybe change the way the negociation step happens. either by using a raw pointer or a lambda ?

**Comment by intelligide** [comment]
I added a new [troubleshoot section ](https://github.com/FrozenStormInteractive/Unreal-SignalR#troubleshooting) in the readme. Concretely, the problem comes from the fact that the functions are asynchronous and that the shared pointer removes the connection object and thus the connection with the server before the negotiation ended. 
You just need to persist a reference to the connection object somewhere in your code.

**Comment by julegault** [comment]
It makes perfect sense, but i would not have figured that out with my beginner level in unreal engine. many thanks !
